from django.utils.translation import ugettext as _


WEATHER_CONDITIONS = {
    200: _('thunderstorm with light rain'),
    201: _('thunderstorm with rain'),
    202: _('thunderstorm with heavy rain'),
    210: _('light thunderstorm'),
    211: _('thunderstorm'),
    212: _('heavy thunderstorm'),
    221: _('ragged thunderstorm'),
    230: _('thunderstorm with light drizzle'),
    231: _('thunderstorm with drizzle'),
    232: _('thunderstorm with heavy drizzle'),
    300: _('light intensity drizzle'),
    301: _('drizzle'),
    302: _('heavy intensity drizzle'),
    310: _('light intensity drizzle rain'),
    311: _('drizzle rain'),
    312: _('heavy intensity drizzle rain'),
    313: _('shower rain and drizzle'),
    314: _('heavy shower rain and drizzle'),
    321: _('shower drizzle'),
    500: _('light rain'),
    501: _('moderate rain'),
    502: _('heavy intensity rain'),
    503: _('very heavy rain'),
    504: _('extreme rain'),
    511: _('freezing rain'),
    520: _('light intensity shower rain'),
    521: _('shower rain'),
    522: _('heavy intensity shower rain'),
    531: _('ragged shower rain'),
    600: _('light snow'),
    601: _('Snow'),
    602: _('Heavy snow'),
    611: _('Sleet'),
    612: _('Light shower sleet'),
    613: _('Shower sleet'),
    615: _('Light rain and snow'),
    616: _('Rain and snow'),
    620: _('Light shower snow'),
    621: _('Shower snow'),
    622: _('Heavy shower snow'),
    701: _('mist'),
    711: _('Smoke'),
    721: _('Haze'),
    731: _('sand/ dust whirls'),
    741: _('fog'),
    751: _('sand'),
    761: _('dust'),
    762: _('volcanic ash'),
    771: _('squalls'),
    781: _('tornado'),
    800: _('clear sky'),
    801: _('few clouds'),
    802: _('scattered clouds'),
    803: _('broken clouds'),
    804: _('overcast clouds'),
}

WEATHER_CONDITIONS_CHOICES = [(k,v) for k,v in WEATHER_CONDITIONS.items()]
