# Generated by Django 3.0.2 on 2020-01-25 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('temp', models.CharField(max_length=100, null=True)),
                ('feels_like', models.CharField(max_length=100, null=True)),
                ('temp_min', models.CharField(max_length=100, null=True)),
                ('temp_max', models.CharField(max_length=100, null=True)),
                ('pressure', models.CharField(max_length=100, null=True)),
                ('sea_level', models.CharField(max_length=100, null=True)),
                ('grnd_level', models.CharField(max_length=100, null=True)),
                ('humidity', models.CharField(max_length=100, null=True)),
                ('temp_kf', models.CharField(max_length=100, null=True)),
                ('weather', models.PositiveIntegerField(choices=[(200, 'thunderstorm with light rain'), (201, 'thunderstorm with rain'), (202, 'thunderstorm with heavy rain'), (210, 'light thunderstorm'), (211, 'thunderstorm'), (212, 'heavy thunderstorm'), (221, 'ragged thunderstorm'), (230, 'thunderstorm with light drizzle'), (231, 'thunderstorm with drizzle'), (232, 'thunderstorm with heavy drizzle'), (300, 'light intensity drizzle'), (301, 'drizzle'), (302, 'heavy intensity drizzle'), (310, 'light intensity drizzle rain'), (311, 'drizzle rain'), (312, 'heavy intensity drizzle rain'), (313, 'shower rain and drizzle'), (314, 'heavy shower rain and drizzle'), (321, 'shower drizzle'), (500, 'light rain'), (501, 'moderate rain'), (502, 'heavy intensity rain'), (503, 'very heavy rain'), (504, 'extreme rain'), (511, 'freezing rain'), (520, 'light intensity shower rain'), (521, 'shower rain'), (522, 'heavy intensity shower rain'), (531, 'ragged shower rain'), (600, 'light snow'), (601, 'Snow'), (602, 'Heavy snow'), (611, 'Sleet'), (612, 'Light shower sleet'), (613, 'Shower sleet'), (615, 'Light rain and snow'), (616, 'Rain and snow'), (620, 'Light shower snow'), (621, 'Shower snow'), (622, 'Heavy shower snow'), (701, 'mist'), (711, 'Smoke'), (721, 'Haze'), (731, 'sand/ dust whirls'), (741, 'fog'), (751, 'sand'), (761, 'dust'), (762, 'volcanic ash'), (771, 'squalls'), (781, 'tornado'), (800, 'clear sky'), (801, 'few clouds'), (802, 'scattered clouds'), (803, 'broken clouds'), (804, 'overcast clouds')], null=True)),
                ('wind_speed', models.CharField(max_length=100, null=True)),
                ('wind_deg', models.CharField(max_length=100, null=True)),
                ('rain', models.CharField(max_length=100, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Location')),
            ],
        ),
    ]
