# Generated by Django 3.0.2 on 2020-01-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=2)),
            ],
        ),
    ]
